### About reduce_mean 

The functionality of numpy.mean and tensorflow.reduce_mean are the *same*

In [0]:
import numpy as np #수학을 다루기 쉽게 해줌 #보통 이걸로 평균내는데, 굳이 텐서플로우에서 평균내는거 또 만듦.
import tensorflow as tf #텐서플로우로 평균내는거 #넘파이랑 비교하려고 만드심

In [2]:
c = np.array([[3.,4], [5.,6], [6.,7]])
print(c)

[[3. 4.]
 [5. 6.]
 [6. 7.]]


In [3]:
m1 = np.mean(c, axis = 1) #axis=1 자리에 1 적어도 된다. 평균을 내는 방향을 지정해주는거. 엑시스가 1이면 가로로(3,4) 평균냄. 0이면 세로로(3,5,6)
print(m1)

[3.5 5.5 6.5]


In [4]:
m2 = tf.reduce_mean(c, axis = 1) #reduce_mean은 평균을 구하는거.
with tf.Session() as sess: #session 안에서만 텐서플로우 실행된다. 
    result = sess.run(m2) #세션부터 본격적으로 실행. run이 돌 때 비로소 결과가 나온다.
    print(result)

[3.5 5.5 6.5]
